language: node_js
os: linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
    - libxi-dev
node_js:
  - '6'
  - '7'
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - npm run build
