language: node_js
os: linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
node_js:
  - '5'
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
