language: node_js
os: linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
    - libxi-dev
node_js:
  - '10'
install:
  - yarn bootstrap
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script:
  - npm run test ci
after_success:
  - cat coverage/lcov.info | coveralls
