// flow-typed signature: 658d10f79c2258c2a56c07892d24093f
// flow-typed version: <<STUB>>/mapbox-gl_v0.50.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mapbox-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mapbox-gl' {
  declare module.exports: any;
}
